### PR TITLE
update upcoming handling for osg 3.6 (SOFTWARE-4482)

### PR DESCRIPTION
**Pull request by edquist**
For the various release scripts, you can now specify release versions as `3.X.Y` and/or `3.X.Y-upcoming` (instead of the previous behavior that took an unversioned `upcoming` argument, and interpreted the latest `3.X.Y` as the upcoming release version, or prompted for one if missing.)

Internally, the existing `$branch` variable (usually returned from `osg_release`) now refers to `3.X` or `3.X-upcoming` instead of `3.X` or `upcoming`.

I think things are looking in a consistent state at this point, but filenames that use `$branch` will now have the `3.X-` prefix before `upcoming`, to match the new series and tag names.  There are a lot of these filenames that are set up in somewhat complicated ways (beyond just the parts touched by this PR), especially in `2-make-notes` and `2-push-release`, that are affected by the new `$branch` semantics ... So @timtheisen please take a peek to see if the downstream effects look right to you.

Also there are a number of cleanups for osg 3.4 and older.

### CODE REVIEW

**Review by matyasselmeci — DISMISSED** [review]
We discussed it on Slack and I would like it if releasing for the 3.5 and 3.5-upcoming repos used the argument `3.5 3.5-upcoming` instead of `3.5 upcoming`.

**Comment by edquist** [comment]
> We discussed it on Slack and I would like it if releasing for the 3.5 and 3.5-upcoming repos used the argument `3.5 3.5-upcoming` instead of `3.5 upcoming`.

So, @matyasselmeci, i totally lied in my ticket description comment the first time around (and have corrected it now).  The old and new behavior was for the main script to take a `3.X.Y` release version and/or an unversioned `upcoming`.  In the case that only `upcoming` is specified, the script (still) prompts for the `3.X.Y` version.

I am not sure if that changes your thoughts about it, since we don't refer to `3.X.Y-upcoming` anywhere ...

**Comment by edquist** [comment]
Also @timtheisen, i would like to ask your thoughts about preferred command line argument formatting, now that the upcoming "series" names get a `3.X-` prefix.

Continue to accept `3.X.Y` and/or `upcoming`, or do something else with upcoming like `3.X.Y-upcoming` or ...?

**Comment by timtheisen** [comment]
For releases we have 3.5.x where is a small integer and is used for repositories and tarball. For OSG 3.6, we decided on 3.6.yymmdd The six digit value is used for tarballs and ignored for repos. Although, I am thinking of making the fixed version in Jira 3.6.yymmdd.

So, for upcoming, you may implement whatever is easiest. We never make upcoming tarballs. So, may need the third value. @matyasselmeci How do we record what got updated in AFS. Would the 3 number be valuable for that?

**Comment by timtheisen** [comment]
@edquist : I think for consistency sake, we would have 3.5.xx and 3.5.xx-upcoming, 3.6.yymmdd and 3.6.yymmdd-upcoming. Does that make sense?

**Comment by matyasselmeci** [comment]
Looks like the records in AFS are done by taking a snapshot of whatever was in release when the script was run.

**Comment by edquist** [comment]
> @edquist : I think for consistency sake, we would have 3.5.xx and 3.5.xx-upcoming, 3.6.yymmdd and 3.6.yymmdd-upcoming. Does that make sense?

Ok, that's fine and makes sense.  I don't really have a preference either way, I just wanted to run it by the people who will actually be using it.

**Comment by edquist** [comment]
Ok, @matyasselmeci & @timtheisen, I've updated things to take `3.X.Y` and/or `3.X.Y-upcoming`.  I did not add 3.6-specific information to enforce that the `Y` in `3.6.Y` is `yymmdd` though.  I can add it if you want, otherwise it's just up to you to specify whatever you want for the release number.

**Comment by timtheisen** [comment]
I don't think that we need enforcement for the version number.

**Review by timtheisen — APPROVED** [review]
I think this looks pretty good. I'll merge it and try it out.

**Pull request merged**
